# Generated by Django 3.2.4 on 2021-06-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210617_2244'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('title', 'slug')},
        ),
    ]
