# Generated by Django 3.2.4 on 2021-06-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210623_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_pk',
            new_name='post',
        ),
    ]
