# Generated by Django 3.2.4 on 2021-07-25 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210623_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=127, verbose_name='description of the image'),
            preserve_default=False,
        ),
    ]
