# Generated by Django 3.2.4 on 2021-08-12 10:54

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_picture_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.CharField(max_length=256, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=127, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=75, size=[800, 400], upload_to='uploads/%Y/%m/%d', verbose_name='Picture as thumbnail'),
        ),
    ]
